# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Tygron
                                 A QGIS plugin
 Use Tygron's computing power inside of QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-10
        copyright            : (C) 2026 by Faris Bontje @ Tygron
        email                : faris@tygron.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Tygron class from file Tygron.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tygron import Tygron
    return Tygron(iface)
